# Column Transformer in Machine Learning - Sklearn

# Problem:
# Different columns in your dataset require different preprocessing steps.
# Example: Age (numeric, impute missing), City & Gender (nominal categorical, one-hot encode),
#          Review (ordinal categorical, ordinal encode)
# Usually, applying transformations individually can be messy and error-prone.

# Solution:
# ColumnTransformer class in sklearn allows you to apply specific transformations to specific columns,
# and then combines the results into a single output.

# Sample Dataset:
# Columns: age (numeric), city (nominal), gender (nominal), review (ordinal)
# Each column requires a different transformation.

# Step 1: Import Necessary Classes
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer

# Step 2: Define the transformers for each type of column

# Example: Suppose you have these columns
# Numerical columns (age, fever): Need missing value imputation
# Ordinal categorical (review): Requires OrdinalEncoder
# Nominal categorical (city, gender): Requires OneHotEncoder

# For missing value imputation (numerical)
num_transformer = SimpleImputer(strategy='mean')

# For ordinal categorical encoding (reviews: ['bad', 'average', 'good', 'excellent'])
ord_transformer = OrdinalEncoder(categories=[['bad', 'average', 'good', 'excellent']])

# For nominal categorical encoding (city, gender)
nom_transformer = OneHotEncoder(drop='first', sparse=False)

# Step 3: Use ColumnTransformer to tie everything together
preprocessor = ColumnTransformer(
    transformers=[
        ('num', num_transformer, ['age', 'fever']),
        ('ord', ord_transformer, ['review']),
        ('nom', nom_transformer, ['city', 'gender'])
    ],
    remainder='drop'  # Drop any columns not specified above
)

# Step 4: Fit and transform your data
# X_train is your input DataFrame
# X_preprocessed = preprocessor.fit_transform(X_train)

# Advantages:
# - Apply different preprocessing to different columns in one pipeline
# - Easily scalable to dozens of columns and transformations
# - Keeps code organized, less error-prone

# Additional Notes:
# - remainder='passthrough' can be used to keep untouched columns.
# - Each transformer tuple: (<name>, <transformer_obj>, <list_of_columns>)
# - ColumnTransformer helps when building robust ML pipelines.

# Example usage:
# from sklearn.pipeline import Pipeline
# full_pipeline = Pipeline(steps=[
#     ('preprocessor', preprocessor),
#     ('classifier', SomeClassifier())
# ])
# model = full_pipeline.fit(X_train, y_train)

# Practice:
# Try creating different transformers for a dataset.
# Combine them with ColumnTransformer for efficient preprocessing.

# Next topics in lecture:
# - How ColumnTransformer integrates with Pipeline for end-to-end ML workflows.

# If you want to practice: Pick any dataset and try applying ColumnTransformer before ML model training.

In [18]:
import numpy as np
import pandas as pd

In [19]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [20]:
df = pd.read_csv('covid_toy.csv')

In [21]:
df.head()

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No


In [22]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [23]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [24]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [29]:
X_train

,age,gender,fever,cough,city
88,5,Female,100.0,Mild,Kolkata
61,81,Female,98.0,Strong,Mumbai
7,20,Female,NaN,Strong,Mumbai
21,73,Male,98.0,Mild,Bangalore
2,42,Male,101.0,Mild,Delhi
...,...,...,...,...,...
12,25,Female,99.0,Strong,Kolkata
90,59,Female,99.0,Strong,Delhi
94,79,Male,NaN,Strong,Kolkata
66,51,Male,104.0,Mild,Kolkata


In [30]:
y_train

88     No
61     No
7     Yes
21    Yes
2      No
     ... 
12     No
90     No
94    Yes
66     No
41    Yes
Name: has_covid, Length: 80, dtype: object

# 1. Without Column Transformer

In [39]:
#adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
X_train_fever.shape

(80, 1)

In [42]:
#OrdinalEncoding -> cough
oe= OrdinalEncoder(categories = [['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

#also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [50]:
#onehotencoding -> gender , city
ohe = OneHotEncoder(drop = 'first',sparse_output = False,dtype=np.int32)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

#also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0,

In [52]:
# extracting age by droping other cols
X_train_age = X_train.drop(columns = ['gender','fever','cough','city']).values

#also for test data
X_test_age = X_test.drop(columns = ['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [56]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis =1)
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis =1)
X_train_transformed

array([[  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 81.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 20.        , 100.78571429,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 73.        ,  98.        ,   1.        ,   0.        ,
          0.        ,   0.        ,   0.        ],
       [ 42.        , 101.        ,   1.        ,   1.        ,
          0.        ,   0.        ,   0.        ],
       [ 56.        , 104.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 19.        , 101.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 17.        , 104.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 14.        ,  99.        ,   0.        ,   0.        ,
          0.    

# 2. Using ColumnTransformer

In [58]:
from sklearn.compose import ColumnTransformer

In [63]:
transformer = ColumnTransformer(transformers = [
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories =[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output = False,drop='first'),['gender','city'])
],remainder = 'passthrough')

In [64]:
transformer.fit_transform(X_train)

array([[100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  81.        ],
       [100.78571429,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [ 98.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  73.        ],
       [101.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  42.        ],
       [104.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  56.        ],
       [101.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  19.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  17.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.    

In [65]:
transformer.transform(X_test)

array([[101.,   0.,   1.,   1.,   0.,   0.,  15.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [ 98.,   0.,   0.,   0.,   0.,   0.,  64.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   0.,   1.,   0.,   1.,   0.,  60.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [103.,   0.,   1.,   0.,   1.,   0.,  83.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [100.,   0.,   1.,   0.,   0.,   0.,  80.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [ 98.,   1.,   1.,   0.,

# Column Transformer on Titanic Dataset

In [66]:
df = pd.read_csv('train.csv')

In [67]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S


In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
